//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nStella.Core.Inwords.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class messages_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal messages_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nStella.Core.Inwords.Resources.messages_en", typeof(messages_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zero.
        /// </summary>
        internal static string Extenso000 {
            get {
                return ResourceManager.GetString("Extenso000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one.
        /// </summary>
        internal static string Extenso001 {
            get {
                return ResourceManager.GetString("Extenso001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two.
        /// </summary>
        internal static string Extenso002 {
            get {
                return ResourceManager.GetString("Extenso002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to three.
        /// </summary>
        internal static string Extenso003 {
            get {
                return ResourceManager.GetString("Extenso003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to four.
        /// </summary>
        internal static string Extenso004 {
            get {
                return ResourceManager.GetString("Extenso004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to five.
        /// </summary>
        internal static string Extenso005 {
            get {
                return ResourceManager.GetString("Extenso005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to six.
        /// </summary>
        internal static string Extenso006 {
            get {
                return ResourceManager.GetString("Extenso006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seven.
        /// </summary>
        internal static string Extenso007 {
            get {
                return ResourceManager.GetString("Extenso007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eight.
        /// </summary>
        internal static string Extenso008 {
            get {
                return ResourceManager.GetString("Extenso008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nine.
        /// </summary>
        internal static string Extenso009 {
            get {
                return ResourceManager.GetString("Extenso009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ten.
        /// </summary>
        internal static string Extenso010 {
            get {
                return ResourceManager.GetString("Extenso010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eleven.
        /// </summary>
        internal static string Extenso011 {
            get {
                return ResourceManager.GetString("Extenso011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twelve.
        /// </summary>
        internal static string Extenso012 {
            get {
                return ResourceManager.GetString("Extenso012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thirteen.
        /// </summary>
        internal static string Extenso013 {
            get {
                return ResourceManager.GetString("Extenso013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourteen.
        /// </summary>
        internal static string Extenso014 {
            get {
                return ResourceManager.GetString("Extenso014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fifteen.
        /// </summary>
        internal static string Extenso015 {
            get {
                return ResourceManager.GetString("Extenso015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sixteen.
        /// </summary>
        internal static string Extenso016 {
            get {
                return ResourceManager.GetString("Extenso016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seventeen.
        /// </summary>
        internal static string Extenso017 {
            get {
                return ResourceManager.GetString("Extenso017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eighteen.
        /// </summary>
        internal static string Extenso018 {
            get {
                return ResourceManager.GetString("Extenso018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nineteen.
        /// </summary>
        internal static string Extenso019 {
            get {
                return ResourceManager.GetString("Extenso019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twenty.
        /// </summary>
        internal static string Extenso020 {
            get {
                return ResourceManager.GetString("Extenso020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thirty.
        /// </summary>
        internal static string Extenso030 {
            get {
                return ResourceManager.GetString("Extenso030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourty.
        /// </summary>
        internal static string Extenso040 {
            get {
                return ResourceManager.GetString("Extenso040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fifty.
        /// </summary>
        internal static string Extenso050 {
            get {
                return ResourceManager.GetString("Extenso050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sixty.
        /// </summary>
        internal static string Extenso060 {
            get {
                return ResourceManager.GetString("Extenso060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seventy.
        /// </summary>
        internal static string Extenso070 {
            get {
                return ResourceManager.GetString("Extenso070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eighty.
        /// </summary>
        internal static string Extenso080 {
            get {
                return ResourceManager.GetString("Extenso080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ninety.
        /// </summary>
        internal static string Extenso090 {
            get {
                return ResourceManager.GetString("Extenso090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one hundred.
        /// </summary>
        internal static string Extenso100 {
            get {
                return ResourceManager.GetString("Extenso100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one hundred.
        /// </summary>
        internal static string Extenso100__ {
            get {
                return ResourceManager.GetString("Extenso100+?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trillion.
        /// </summary>
        internal static string Extenso1e12plural {
            get {
                return ResourceManager.GetString("Extenso1e12plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trillion.
        /// </summary>
        internal static string Extenso1e12singular {
            get {
                return ResourceManager.GetString("Extenso1e12singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quadrillion.
        /// </summary>
        internal static string Extenso1e15plural {
            get {
                return ResourceManager.GetString("Extenso1e15plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quadrillion.
        /// </summary>
        internal static string Extenso1e15singular {
            get {
                return ResourceManager.GetString("Extenso1e15singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quintillion.
        /// </summary>
        internal static string Extenso1e18plural {
            get {
                return ResourceManager.GetString("Extenso1e18plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quintillion.
        /// </summary>
        internal static string Extenso1e18singular {
            get {
                return ResourceManager.GetString("Extenso1e18singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sextillion.
        /// </summary>
        internal static string Extenso1e21plural {
            get {
                return ResourceManager.GetString("Extenso1e21plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sextillion.
        /// </summary>
        internal static string Extenso1e21singular {
            get {
                return ResourceManager.GetString("Extenso1e21singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to septillion.
        /// </summary>
        internal static string Extenso1e24plural {
            get {
                return ResourceManager.GetString("Extenso1e24plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to septillion.
        /// </summary>
        internal static string Extenso1e24singular {
            get {
                return ResourceManager.GetString("Extenso1e24singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to octillion.
        /// </summary>
        internal static string Extenso1e27plural {
            get {
                return ResourceManager.GetString("Extenso1e27plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to octillion.
        /// </summary>
        internal static string Extenso1e27singular {
            get {
                return ResourceManager.GetString("Extenso1e27singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nonillion.
        /// </summary>
        internal static string Extenso1e30plural {
            get {
                return ResourceManager.GetString("Extenso1e30plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nonillion.
        /// </summary>
        internal static string Extenso1e30singular {
            get {
                return ResourceManager.GetString("Extenso1e30singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decillion.
        /// </summary>
        internal static string Extenso1e33plural {
            get {
                return ResourceManager.GetString("Extenso1e33plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decillion.
        /// </summary>
        internal static string Extenso1e33singular {
            get {
                return ResourceManager.GetString("Extenso1e33singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undecillion.
        /// </summary>
        internal static string Extenso1e36plural {
            get {
                return ResourceManager.GetString("Extenso1e36plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undecillion.
        /// </summary>
        internal static string Extenso1e36singular {
            get {
                return ResourceManager.GetString("Extenso1e36singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duodecillion.
        /// </summary>
        internal static string Extenso1e39plural {
            get {
                return ResourceManager.GetString("Extenso1e39plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duodecillion.
        /// </summary>
        internal static string Extenso1e39singular {
            get {
                return ResourceManager.GetString("Extenso1e39singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thousand.
        /// </summary>
        internal static string Extenso1e3plural {
            get {
                return ResourceManager.GetString("Extenso1e3plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thousand.
        /// </summary>
        internal static string Extenso1e3singular {
            get {
                return ResourceManager.GetString("Extenso1e3singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tredecillion.
        /// </summary>
        internal static string Extenso1e42plural {
            get {
                return ResourceManager.GetString("Extenso1e42plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tredecillion.
        /// </summary>
        internal static string Extenso1e42singular {
            get {
                return ResourceManager.GetString("Extenso1e42singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to million.
        /// </summary>
        internal static string Extenso1e6plural {
            get {
                return ResourceManager.GetString("Extenso1e6plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to million.
        /// </summary>
        internal static string Extenso1e6singular {
            get {
                return ResourceManager.GetString("Extenso1e6singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to billion.
        /// </summary>
        internal static string Extenso1e9plural {
            get {
                return ResourceManager.GetString("Extenso1e9plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to billion.
        /// </summary>
        internal static string Extenso1e9singular {
            get {
                return ResourceManager.GetString("Extenso1e9singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two hundred.
        /// </summary>
        internal static string Extenso200 {
            get {
                return ResourceManager.GetString("Extenso200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to three hundred.
        /// </summary>
        internal static string Extenso300 {
            get {
                return ResourceManager.GetString("Extenso300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to four hundred.
        /// </summary>
        internal static string Extenso400 {
            get {
                return ResourceManager.GetString("Extenso400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to five hundred.
        /// </summary>
        internal static string Extenso500 {
            get {
                return ResourceManager.GetString("Extenso500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to six hundred.
        /// </summary>
        internal static string Extenso600 {
            get {
                return ResourceManager.GetString("Extenso600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seven hundred.
        /// </summary>
        internal static string Extenso700 {
            get {
                return ResourceManager.GetString("Extenso700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eight hundred.
        /// </summary>
        internal static string Extenso800 {
            get {
                return ResourceManager.GetString("Extenso800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nine hundred.
        /// </summary>
        internal static string Extenso900 {
            get {
                return ResourceManager.GetString("Extenso900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ \and\ .
        /// </summary>
        internal static string Extensosep {
            get {
                return ResourceManager.GetString("Extensosep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Extensosepdezena {
            get {
                return ResourceManager.GetString("Extensosepdezena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Extensosepformato {
            get {
                return ResourceManager.GetString("Extensosepformato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \,\ .
        /// </summary>
        internal static string Extensosepmil {
            get {
                return ResourceManager.GetString("Extensosepmil", resourceCulture);
            }
        }
    }
}
